### ISSUE TITLE
App hangs after ~4000 scanned ports

### ISSUE THREAD

**Issue by mirh** [aaronjwood/PortAuthority#29] opened 2016-04-11 15:57 UTC
Theoretically, you should have also just received my feedback.

**Comment by aaronjwood** [comment] 2016-04-11 18:08
I just looked at the specs of the phone you have and I think that it might be cutting it close to what's needed to run this app. The issue is that port scans are heavily threaded, so a phone with 1 GB of RAM and 2 cores might have trouble with large scans against a host that sends back RST packets (or ICMP destination not reachable packets) immediately.

What I can do to help alleviate this issue is make the amount of threads used to scan ports a setting and set the default to what it is now in the code. That way you could lower the amount of threads to something the hardware can better handle. Currently there are about 500 threads used for port scans and the downside to that is that older hardware will have a tough time handling that much activity. The upside is that it's what gives the app it's speed so people don't have to wait 30 minutes to scan 30,000 ports :)

**Comment by mirh** [comment] 2016-04-11 20:31
:\ I rebooted, cleared recent processes.. Now it works. 
And it doesn't really seem to occupy a lot of RAM.

**Comment by aaronjwood** [comment] 2016-04-11 21:51
Yeah, it's really the CPU that gets hit hard. If you have a version of Android < 5.x it'll be worse due to the Dalvik VM. The new ART runtime is much better in many ways :)

**Comment by mirh** [comment] 2016-04-12 18:09
I am on 5.1 btw.

**Comment by aaronjwood** [comment] 2016-05-26 02:59
Setting to control how many threads is used is implemented and will be in the next release. See 2c277316a7760358a4a7c4adbeec16de42471971 efe6364dbb1ccfe0bcdf70fdc36ab99377ff83f5

**Closed by aaronjwood** 2016-05-26 02:59 UTC
Labels: bug

**Comment by mirh** [comment] 2016-12-24 20:58
Just tested latest version, and both 10 and 500 seems to work (for as much the latter has some "lows" every now and then)
